"""empty message

Revision ID: a8fdf4253741
Revises: c4627ddd840d
Create Date: 2021-10-14 11:05:12.512997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8fdf4253741'
down_revision = 'c4627ddd840d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('product_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_description')
    # ### end Alembic commands ###
